name: 'Corne 6-column'
on:
  workflow_dispatch:
  push:
    paths:
      - 'corne_6-column.yaml'
      - 'config/corne_6-column.conf'
      - 'config/corne_6-column.keymap'
      - 'config/corne_6-column.yaml'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: scorne_6-column.yaml
      archive_name: corne_6-column
