name: 'Corne White'
on:
  workflow_dispatch:
  push:
    paths:
      - 'includes/*'
      - 'config_white/*'

jobs:
  build_white:
    # https://github.com/zmkfirmware/zmk/blob/main/.github/workflows/build-user-config.yml
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: corne_white_build.yaml            # default: "build.yaml"
      config_path: config_white                            # default: "config"
      archive_name: corne_white                            # default: "firmware"
