name: 'Corne White'
on:
  workflow_dispatch:
  push:
    paths:
      - '*build.yaml'
      - 'includes/*'
      - 'config/corne_white*'

jobs:
  build:
    # https://github.com/zmkfirmware/zmk/blob/main/.github/workflows/build-user-config.yml
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: corne_white_build.yaml            # default: "build.yaml"
      archive_name: corne_white                            # default: "firmware"
